### ISSUE TITLE
Failed to infer field type for MySQL `blob` field

### ISSUE THREAD

**Issue by muniter** [lorefnon/ts-sql-codegen#11]
Trying to generate classes from a table with a [BLOB field](https://dev.mysql.com/doc/refman/8.0/en/blob.html) in MySQL throws an error.

**Comment by juanluispaz** [comment]
See https://github.com/lorefnon/ts-sql-codegen/issues/12#issuecomment-1384048442

**Comment by muniter** [comment]
I think it is better to explicitly map blob.
