### ISSUE TITLE
Failed to infer field type for MySQL `ENUM` field

### ISSUE THREAD

**Issue by muniter** [lorefnon/ts-sql-codegen#12]
Trying to generate classes from a table with a [ENUM field](https://dev.mysql.com/doc/refman/8.0/en/enum.html) in MySQL throws an error.

**Comment by lorefnon** [comment]
Hi @muniter, you are perhaps the first person to use the codegen utility with mysql.

I'll update the regex patterns for the primitive types like char, decimal etc. however for composite types like enum or json you will need to define a [type adapter](https://github.com/lorefnon/ts-sql-codegen#custom-db-types) and pass it to the generator.

The tool we rely on to dump the schema (tbls) does not provide us with enough info to infer the enum completely. I had opened [an issue](https://github.com/k1LoW/tbls/issues/357) with them sometime back.

**Comment by juanluispaz** [comment]
Hi,

The generator, by default, only map types that clear, unambiguous and safe type in JS/TS, for the other types you will need to map the corresponding type using a [field mapping](https://github.com/lorefnon/ts-sql-codegen/blob/main/docs/interfaces/GeneratorOpts.md#fieldmappings) in a similar way the [default ones are defined](https://github.com/lorefnon/ts-sql-codegen/blob/284ea4867fe73060ce01089064cb057cc8df0c60/src/field-mappings.ts#L129). Example:

```ts
const options: GeneratorOpts = {
  schemaPath: './db/schema.yaml',
  connectionSourcePath: './src/db.connection.ts',
  outputDirPath: './src/db',
  fieldMappings: [
    {
      columnType: /^numeric$/,
      generatedField: { type: { dbType: { name: "stringDouble" } } }
    }
  ],
  export: {
    tableInstances: true,
    rowTypes: true,
    extractedColumns: true
  }
}

const generator = new Generator(options);
await generator.generate();
```

For more complex types you will need more complex rules, where there are not a generic type representation, like ENUM, JSON, etc. you will need to follow the [ones described here](https://github.com/lorefnon/ts-sql-codegen#custom-db-types)

**Comment by muniter** [comment]
Hello, thank you very much for the project, I hope the multiple issues wasn't taken as noise!

Thanks for the quick response!

@juanluispaz Noted, makes perfect sense. Will close the issues on the complex types.
