### ISSUE TITLE
Support difference cases naming would be helpful

### ISSUE THREAD

**Issue by yeongjet** [lorefnon/ts-sql-codegen#6]
The output files name is pascal case naming by default, I would like to use others, like camel case.

**Comment by lorefnon** [comment]
If you are using the generator programmatically you can extend the generator to support custom naming convention: 

```ts
const { Generator } = require('ts-sql-codegen');
const { lowerFirst } = require('lodash');

class CustomGenerator extends Generator {
  getOutputFileName(table, tableKind) {
    return lowerFirst(super.getOutputFileName(table, tableKind))
  }
}

const options = {
   schemaPath: './schema.yaml',
   connectionSourcePath: './connection-source.ts'
}

const generator = new Generator(options);
await generator.generate();
```

**Comment by lorefnon** [comment]
I'll add some options for common naming conventions like camel case and underscore, but for custom naming conventions extending generator is the most flexible option

**Comment by yeongjet** [comment]
Thanks，help me a lot.
