### ISSUE TITLE
Failed to infer field type for mysql `CHAR` field.

### ISSUE THREAD

**Issue by muniter** [lorefnon/ts-sql-codegen#8]
Trying to generate classes from a table with a [`CHAR` field](https://dev.mysql.com/doc/refman/8.0/en/char.html) in MySQL throws an error. Perhaps another branch in the regex here https://github.com/lorefnon/ts-sql-codegen/blob/9bf567c93162bb493ae13d7ed6a669e61ef51303/src/field-mappings.ts#L131

Could fix the issue?

**Comment by juanluispaz** [comment]
See https://github.com/lorefnon/ts-sql-codegen/issues/12#issuecomment-1384048442

**Comment by lorefnon** [comment]
Please use 3.7.2
