### ISSUE TITLE
Failed to infer field type for MySQL `decimal` field

### ISSUE THREAD

**Issue by muniter** [lorefnon/ts-sql-codegen#9]
Trying to generate classes from a table with a [DECIMAL field](https://dev.mysql.com/doc/refman/8.0/en/fixed-point-types.html) in MySQL throws an error.

**Comment by juanluispaz** [comment]
See https://github.com/lorefnon/ts-sql-codegen/issues/12#issuecomment-1384048442

**Comment by lorefnon** [comment]
Please use 3.7.2
